"""
AUTOGENERATED by git post-commit hook. Note that these are always from the PREVIOUS commit, and so may be out of date by one log entry
"""
git_branch    = "master"
git_shorthash = "11521c7"
git_longhash  = "11521c7a3b8ccd0b1aa25960a2b1c1ffe3d51c5f"
git_last_tag  = "1.2.0"
