"""
AUTOGENERATED by git post-commit hook. Note that these are always from the PREVIOUS commit, and so may be out of date by one log entry
"""
git_branch    = "master"
git_shorthash = "a3dab3d"
git_longhash  = "a3dab3d8ce5b0249974b14a5b6b03c4a2ece11e9"
git_last_tag  = "1.0.1.rc1"
