"""
AUTOGENERATED by git post-commit hook. Note that these are always from the PREVIOUS commit, and so may be out of date by one log entry
"""
git_branch    = "master"
git_shorthash = "5e67eac"
git_longhash  = "5e67eac1da383a77f11fc65c1557cab2317a55c2"
git_last_tag  = "1.1.1"
